"""Regenerates the five pricing pages from central locale and product data.
Run from the repository root: python scripts/build_core_pages.py
"""
from pathlib import Path
import json, html
ROOT=Path(__file__).resolve().parents[1]
PRODUCT=json.loads((ROOT/'config/product.json').read_text(encoding='utf-8'))
LOCALES=json.loads((ROOT/'content/core-locales.json').read_text(encoding='utf-8'))
URLS={'de':'https://www.lingroo.app/de/preise/','pl':'https://www.lingroo.app/pl/cennik/','en':'https://www.lingroo.app/en/pricing/','ua':'https://www.lingroo.app/ua/tsiny/','ru':'https://www.lingroo.app/ru/ceny/'}
LANG={'de':'de','pl':'pl','en':'en','ua':'uk','ru':'ru'}
VALUES=[997,750,320,80,40,6,30,14]
LEGAL_HREFS=['https://www.lingroo.de/impressum','https://www.lingroo.de/datenschutz','https://www.lingroo.de/agb','https://www.lingroo.de/widerruf','mailto:hello@lingroo.de?subject=K%C3%BCndigung%20Lingroo%20Premium']

def page(code,L):
    canonical=URLS[code]
    alts=''.join(f'<link rel="alternate" hreflang="{LANG[k]}" href="{v}">' for k,v in URLS.items())+'<link rel="alternate" hreflang="x-default" href="https://www.lingroo.app/de/preise/">'
    app={"@context":"https://schema.org","@type":"SoftwareApplication","name":"Lingroo","applicationCategory":"EducationalApplication","operatingSystem":"Web, PWA","url":"https://www.lingroo.de/","description":L['desc'],"offers":{"@type":"Offer","price":f"{PRODUCT['price']:.2f}","priceCurrency":PRODUCT['currency'],"availability":"https://schema.org/InStock"}}
    faq={"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}} for q,a in L['faqs']]}
    features=''.join(f'<article class="feature"><h3>{html.escape(h)}</h3><p>{html.escape(p)}</p></article>' for h,p in L['features'])
    stats=''.join(f'<div class="stat"><strong>{v}</strong><span>{html.escape(lbl)}</span></div>' for v,lbl in zip(VALUES,L['labels']))
    rows=''.join('<tr>'+''.join(f'<td class="{"limited" if i==1 else "yes" if i>1 else ""}">{html.escape(str(x))}</td>' for i,x in enumerate(row))+'</tr>' for row in L['rows'])
    faqs=''.join(f'<details><summary>{html.escape(q)}</summary><p>{html.escape(a)}</p></details>' for q,a in L['faqs'])
    legal=' · '.join(f'<a href="{href}">{html.escape(label)}</a>' for href,label in zip(LEGAL_HREFS,L['legal']))
    price_display=str(PRODUCT['price']).replace('.',',')
    return f'''<!doctype html><html lang="{LANG[code]}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(L['title'])}</title><meta name="description" content="{html.escape(L['desc'])}"><link rel="canonical" href="{canonical}">{alts}<meta property="og:type" content="website"><meta property="og:title" content="{html.escape(L['title'])}"><meta property="og:description" content="{html.escape(L['desc'])}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="https://www.lingroo.app/og-lingroo.png"><link rel="icon" href="/icons/icon-192.png"><link rel="stylesheet" href="/assets/pricing.css"><script type="application/ld+json">{json.dumps(app,ensure_ascii=False)}</script><script type="application/ld+json">{json.dumps(faq,ensure_ascii=False)}</script></head><body>
<nav class="p-nav"><div class="p-container p-nav-inner"><a class="p-brand" href="{L['home']}"><span class="p-mark">L</span><span>Lingroo</span></a><div class="p-links"><a href="{L['home']}">{html.escape(L['nav_home'])}</a><a href="#umfang">{html.escape(L['nav_scope'])}</a><a href="#vergleich">{html.escape(L['nav_price'])}</a></div><a class="p-app" href="https://www.lingroo.de/?utm_source=lingroo_app&utm_medium=pricing&utm_campaign=soft_launch&utm_content={code}">{html.escape(L['open'])}</a></div></nav>
<header class="p-hero"><div class="p-container p-grid"><div><span class="p-kicker">{html.escape(L['kicker'])}</span><h1>{html.escape(L['h1'])}</h1><p>{html.escape(L['intro'])}</p><div class="p-actions"><a class="p-btn p-btn-primary" href="https://www.lingroo.de/?utm_source=lingroo_app&utm_medium=pricing&utm_campaign=trial&utm_content={code}">{html.escape(L['trial'])}</a><a class="p-btn p-btn-secondary" href="#vergleich">{html.escape(L['compare'])}</a></div></div><aside class="price-card"><span class="price-badge">{html.escape(L['phase'])}</span><h2>Premium</h2><div class="price">{price_display} € <small>/ {html.escape(L['month'])}</small></div><p>{html.escape(L['price_note'])}</p><div class="checklist">{''.join(f'<div><span class="check">✓</span><span>{html.escape(c)}</span></div>' for c in L['checks'])}</div><a class="p-btn p-btn-primary" style="width:100%" href="https://www.lingroo.de/?utm_source=lingroo_app&utm_medium=pricing&utm_campaign=checkout&utm_content={code}">{html.escape(L['trial'])}</a></aside></div></header>
<main class="p-main"><div class="p-container"><section class="p-section" id="umfang"><h2>{html.escape(L['what_h'])}</h2><p>{html.escape(L['what_p'])}</p><div class="feature-grid">{features}</div></section><section class="p-section"><h2>{html.escape(L['inventory_h'])}</h2><p>{html.escape(L['inventory_p'])}</p><div class="stats">{stats}</div></section><section class="p-section"><h2>{html.escape(L['writing_h'])}</h2><p>{html.escape(L['writing_p'])}</p><div class="writing-demo"><div class="writing-box"><span>{html.escape(L['simple'])}</span><p>{html.escape(L['simple_ex'])}</p></div><div class="writing-box good"><span>{html.escape(L['formal'])}</span><p>{html.escape(L['formal_ex'])}</p></div></div></section><section class="p-section" id="vergleich"><h2>{html.escape(L['compare_h'])}</h2><div class="compare"><table><thead><tr>{''.join(f'<th>{html.escape(c)}</th>' for c in L['cols'])}</tr></thead><tbody>{rows}</tbody></table></div><div class="notice" style="margin-top:20px">{html.escape(L['b2_note'])}</div></section><section class="p-section"><h2>{html.escape(L['limits_h'])}</h2><div class="notice">{html.escape(L['limits'])}</div></section><section class="p-section"><h2>{html.escape(L['faq_h'])}</h2><div class="faq">{faqs}</div></section></div></main><footer class="p-footer"><div class="p-container"><strong>Lingroo</strong><p>{html.escape(L['footer'])}</p><div class="lang-row"><a href="/de/preise/">DE</a><a href="/pl/cennik/">PL</a><a href="/en/pricing/">EN</a><a href="/ua/tsiny/">UA</a><a href="/ru/ceny/">RU</a></div><p>{legal}</p></div></footer></body></html>'''

for code,L in LOCALES.items():
    target=ROOT/L['path']/'index.html'; target.parent.mkdir(parents=True,exist_ok=True); target.write_text(page(code,L),encoding='utf-8')
print('Generated pricing pages:',len(LOCALES))
